# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dezycro < Formula
  desc "Dezycro for AI coding agents"
  homepage "https://dezycro.ai"
  version "3.20.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dezycro/cli-releases/releases/download/v3.20.0/dezycro_3.20.0_darwin_amd64.tar.gz"
      sha256 "630f20ddeeb089eac3a0ef83c086c4eb16a233a4310cd6dbaa19dae86501807b"

      define_method(:install) do
        libexec.install "dezycro", "skills", "prompts", "hooks", ".claude-plugin"
        bin.write_exec_script libexec/"dezycro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dezycro/cli-releases/releases/download/v3.20.0/dezycro_3.20.0_darwin_arm64.tar.gz"
      sha256 "58ee0028c6cfb922a58a41dc5e0d3ccf84164898c6e55e9f44bb9cc319575bb6"

      define_method(:install) do
        libexec.install "dezycro", "skills", "prompts", "hooks", ".claude-plugin"
        bin.write_exec_script libexec/"dezycro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dezycro/cli-releases/releases/download/v3.20.0/dezycro_3.20.0_linux_amd64.tar.gz"
      sha256 "45c28f8b99f30d9e6b37e1ffee5df828454eac7cf17dadea206b6a5722f8cc10"
      define_method(:install) do
        libexec.install "dezycro", "skills", "prompts", "hooks", ".claude-plugin"
        bin.write_exec_script libexec/"dezycro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dezycro/cli-releases/releases/download/v3.20.0/dezycro_3.20.0_linux_arm64.tar.gz"
      sha256 "9987ee88165b5742f7fc497abbbcc3452b85bcb1d3cf14dd8c20f0e528207518"
      define_method(:install) do
        libexec.install "dezycro", "skills", "prompts", "hooks", ".claude-plugin"
        bin.write_exec_script libexec/"dezycro"
      end
    end
  end

  def caveats
    <<~EOS
      dezycro is proprietary software. Use is subject to the Dezycro EULA:
        dezycro license

      Connect to the Dezycro platform (one time):
        dezycro setup
    EOS
  end

  test do
    system "#{bin}/dezycro", "--version"
  end
end
